### ISSUE TITLE
Make it easier to copy the generated hash

### ISSUE THREAD

**Issue by fbidu** [fbidu/larapass#1]
Users suggested on the [comments of a Facebook post](https://www.facebook.com/groups/laravelbrasil/permalink/949911061697616/) that copying the hash should be easier. Suggestions are:
- Put the generated hash inside an `input`
- Automatically copy the hash to the clipboard after clicking on it

**Comment by rmobis** [comment]
Putting the generated hash inside an input doesn't help that much and automatically copying to clipboard isn't easy (requires either Flash or poorly supported APIs), apart from being rather intrusive. 

What about going for something along the lines of what http://goo.gl does? After shortening your URL, they simply select the text and then you can just Ctrl + V if you want to. This strikes me as both better and easier to implement.

**Comment by fbidu** [comment]
I don't like Flash either because of security reasons but it seem that there are some simple implementations available [jQuery copy plugin](https://sites.google.com/site/yangshuai10/jquerycopyplugin) and [ZeroClipboard](http://zeroclipboard.org).

Honestly, I'd like to try them just for the HUE but I do agree that the goo.gl solution is very nice :D

**Comment by rmobis** [comment]
The issue with both ZeroClipboard (which I've used in the past and is
really good) and the jQuery plugin is that they both use Flash and given
that Chrome (and recently Firefox, even if temporarily) has disabled it by
default, it doesn't seem like a lasting solution. It would seem like moving
in the opposite direction when compared to the rest of the world.

_Raphael Mobis Tacla_
Graduando em Engenharia de Computação @ Universidade Estadual de Campinas
Assistente de Desenvolvimento @ Associação Atlética Acadêmica da Ciência e
Engenharia de Computação
+55 19 99665-6606

**Comment by fbidu** [comment]
Okay, you got me. My only concern now is about the look and feel. I used this project to test the use of a color palette on a single page app. As of now, the selected text looks rather ugly
![captura de tela de 2015-07-20 14 15 12](https://cloud.githubusercontent.com/assets/247856/8782137/cef8b9b6-2ee9-11e5-81e8-c7c6f04a041d.png)

I wonder if there is a way to show that the text is selected while keeping the design coherent.

**Comment by fbidu** [comment]
[Maybe this?](https://css-tricks.com/overriding-the-default-text-selection-color-with-css/)

**Comment by rmobis** [comment]
Ye, that's what I was about to suggest. That's beyond my field of
expertise, but the yellow you used on the header seems like a good
candidate.

Either way, since you'll mess with styling, why not get a monospaced font
for the hash?

_Raphael Mobis Tacla_
Graduando em Engenharia de Computação @ Universidade Estadual de Campinas
Assistente de Desenvolvimento @ Associação Atlética Acadêmica da Ciência e
Engenharia de Computação
+55 19 99665-6606

**Comment by rmobis** [comment]
Also, the article you linked to mentions `::selection` had limited support
at the time. Nowadays, all browsers (with the exception of iOS Safari and
Opera Mini) support it and FireFox is the only to have it vendor prefixed.

http://caniuse.com/#search=selection

_Raphael Mobis Tacla_
Graduando em Engenharia de Computação @ Universidade Estadual de Campinas
Assistente de Desenvolvimento @ Associação Atlética Acadêmica da Ciência e
Engenharia de Computação
+55 19 99665-6606

**Comment by fbidu** [comment]
Where's David? Hahaha

**Comment by fbidu** [comment]
@dsfugimoto?

**Comment by rmobis** [comment]
Hahahahah. Forwarding this thread to his e-mail.

**Comment by dsfugimoto** [comment]
Change the default background of selected items to yellow and add that darker color (the one used on website background) on the font color.

**Comment by rmobis** [comment]
Gee, I'm getting good at this.

**Comment by fbidu** [comment]
@dsfugimoto seems nice! Gonna branch 'n try

**Comment by fbidu** [comment]
Made this, what do you guys think?
![captura de tela de 2015-07-20 14 52 12](https://cloud.githubusercontent.com/assets/247856/8782918/f6f03cfa-2eee-11e5-9512-e2f672899aab.png)

**Comment by rmobis** [comment]
Pretty good. Monospaced font pls?

_Raphael Mobis Tacla_
Graduando em Engenharia de Computação @ Universidade Estadual de Campinas
Assistente de Desenvolvimento @ Associação Atlética Acadêmica da Ciência e
Engenharia de Computação
+55 19 99665-6606

**Comment by fbidu** [comment]
It crashes on Chrome! 
![captura de tela de 2015-07-20 15 24 35](https://cloud.githubusercontent.com/assets/247856/8783616/760b2e4c-2ef3-11e5-88dc-3d66489d0eaf.png)

**Comment by fbidu** [comment]
Apparently, Chrome itself has issues with text selections... https://code.google.com/p/chromium/issues/detail?id=491501

**Comment by rmobis** [comment]
It's even worse on my Chrome (43, W8). To be honest, it never bothered me.

**Comment by rmobis** [comment]
Maybe decreasing `font-size` so that it fits into a single line works better?

**Comment by fbidu** [comment]
Really? Post a screenshot!

**Comment by fbidu** [comment]
I got this... Monospaced, one liner 
![captura de tela de 2015-07-20 16 13 23](https://cloud.githubusercontent.com/assets/247856/8784849/4e82e78c-2efa-11e5-8225-c57e879264d7.png)

**Comment by fbidu** [comment]
@dsfugimoto did a little research around selecting content... It seems a little troublesome as well http://stackoverflow.com/questions/9975707/use-jquery-select-to-select-contents-of-a-div

**Comment by fbidu** [comment]
You see, this really bugs me. This sort of thing - allowing the user to easily get a simple string into its clipboard - should be easier!

**Comment by fbidu** [comment]
May I quote Linus _fuc%ing_ Torvalds here? :stuck_out_tongue:

**Comment by rmobis** [comment]
It should be easier, but it also incurs into privacy issues. That's why it's complicated. Anyway, goo.gl seems to use a readonly input. Tried that?

**Comment by fbidu** [comment]
@rmobis It creates privacy troubles only if it allows for the site to _read_ the contents from the clipboard. If there were an API with write-only access to the clipboard, there shouldn't be much problem...

**Comment by fbidu** [comment]
@rmobis Checking goo.gl now!

**Comment by rmobis** [comment]
It still creates privacy problems because when you write, you actually **over**write. Maybe I have something important on my clipboard that I don't want erased.

**Comment by fbidu** [comment]
True that... But it seems less concerning than reading

**Comment by rmobis** [comment]
There's a spec coming for this (Clipboard API) but it's not really widely
supported atm.

_Raphael Mobis Tacla_
Graduando em Engenharia de Computação @ Universidade Estadual de Campinas
Assistente de Desenvolvimento @ Associação Atlética Acadêmica da Ciência e
Engenharia de Computação
+55 19 99665-6606

**Comment by fbidu** [comment]
@rmobis well, it's good to know! Considering that Chrome and Firefox are open source or open source-based, I think it would be a nice exercise for the three of us to go into their projects, check if there's a discussion or implementation going on and participate/propose! We would get a very nice experience on contributing to open source and working on large code bases with other people while contributing to solve a problem we all agree exists. What do you think, @dsfugimoto?

**Comment by rmobis** [comment]
@fbidu yeah, I don't think I'm engaged enough for that...

_Raphael Mobis Tacla_
Graduando em Engenharia de Computação @ Universidade Estadual de Campinas
Assistente de Desenvolvimento @ Associação Atlética Acadêmica da Ciência e
Engenharia de Computação
+55 19 99665-6606

**Comment by fbidu** [comment]
Oh, come on! It will be fun

--F. Bidu
Em 20/07/2015 21:17, "Raphael Mobis Tacla" notifications@github.com
escreveu:

**Comment by fbidu** [comment]
Well, going back to the issue, it seems that the selection color on Chrome is skewed towards an orange tone. @rmobis suggested on a talk at the _pastelaria_ yesterday that it could be due to opacity. [This post](http://stackoverflow.com/questions/14970891/css-selection-color-behaving-strangely-on-chrome) gives me some clues. I'm gonna try them.

Issue:
Selection in Chrome, color displayed: `#D3792B`
![captura de tela de 2015-07-22 09 12 13](https://cloud.githubusercontent.com/assets/247856/8825014/c8fe6524-3051-11e5-9e05-7aacaeede376.png)

Selection in FF, color displayed: `#ECD078`
![captura de tela de 2015-07-22 09 13 12](https://cloud.githubusercontent.com/assets/247856/8825033/fe69ae58-3051-11e5-9d3c-9ee812c1e78a.png)

**Comment by fbidu** [comment]
Yes, it worked! It was all a matter to change from `background: #ECD078;` to `background-color: rgba(236,208,120,.99)`

**Comment by fbidu** [comment]
@dsfugimoto strange behavior here... I have the following rules on the css:

``` css
::selection
{
    background-color: rgba(236,208,120,.99);
}

::-moz-selection
{
    background-color: rgba(236,208,120,.99);
}
```

since they are basically the same rule, I figured I could just merge them together:

``` css
::-moz-selection, ::selection
{
    background-color: rgba(236,208,120,.99);
}
```

but it didn't work! The rule wasn't applied to any browsers. Any idea?

**Comment by dsfugimoto** [comment]
@fbidu read this question on StackOverflow:

http://stackoverflow.com/questions/16982449/why-isnt-it-possible-to-combine-vendor-specific-pseudo-elements-classes-into-on

**Comment by fbidu** [comment]
@dsfugimoto Very interesting! Thanks!

**Comment by fbidu** [comment]
UPDATE: I changed the `<h3>` element where the hash value was being assigned to an input, managed to select its contents through a simple jQuery and I am almost done styling it :D

**Comment by fbidu** [comment]
Done! I'll commit and open a pull request

**Comment by rmobis** [comment]
:+1:

**Comment by dsfugimoto** [comment]
I suggest one style modification. Add vertical-align to the content:

``` css
.container {
    transform: translate(-50%, -50%);
    top: 50%;
    left: 50%;
    position: absolute;
}
```

**Comment by fbidu** [comment]
@dsfugimoto done!

**Comment by rmobis** [comment]
That's a pretty neat trick, @dsfugimoto

_Raphael Mobis Tacla_
Graduando em Engenharia de Computação @ Universidade Estadual de Campinas
Assistente de Desenvolvimento @ Associação Atlética Acadêmica da Ciência e
Engenharia de Computação
+55 19 99665-6606

**Comment by fbidu** [comment]
Pull request #2  accepted! Issue closed
